<?php
    /** @var \MageSuite\ProductTile\Block\Tile\Container $this */
    $layout = $this->getLayout();
    $htmlTag = !empty($block->getHtmlTag()) ? $block->getHtmlTag() : 'div';
    $cssClass = $block->getCssClass() ? 'class="'.$block->getCssClass().'"' : '';
    $shouldRenderEmpty = !empty($block->getRenderEmpty()) ? $block->getRenderEmpty() : false;
    $output = '';

    foreach($this->getChilds() as $child) {
        $child->setTile($block->getTile());
        $output .= $layout->renderElement($child->getNameInLayout(), false);
    }

    // Render the container if 'render_empty' container attribute is set to 'true' or if there is any output
    if (!$shouldRenderEmpty && !trim($output)) { return; }
?>
<<?= $htmlTag ?> <?= $cssClass ?>><?=$output?></<?= $htmlTag ?>>
