<?php
    $layout = $this->getLayout();
    $cssClass = $block->getCssClass() ? 'class="'.$block->getCssClass().'"' : '';
    $output = '';

    foreach($this->getChilds() as $child) {
        $child->setTile($block->getTile());
        $output .= $layout->renderElement($child->getNameInLayout(), false);
    }
?>

<a href="<?= $block->getProduct()->getProductUrl() ?>" <?= $cssClass ?>><?=$output?></a>
