<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$repository = $objectManager->create(\Magento\Catalog\Api\ProductRepositoryInterface::class);

$products = ['24-MB01', '24-MB04', '24-WG080','24-WB04', 'WSH12'];

$iterator = 1;
?>

<ol class="cs-grid-layout__grid">
    <?php foreach ($products as $sku): ?>
        <li class="cs-grid-layout__brick ">
            <?php
            $product = $repository->get($sku);

            echo $this->getLayout()
                ->createBlock(\MageSuite\ProductTile\Block\Tile::class)
                ->setType('grid')
                ->setIterator($iterator)
                ->setSection('category')
                ->render($product);
            ?>
        </li>
        <?php $iterator++; ?>
    <?php endforeach; ?>
</ol>

<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
    </script>
<?php endif; ?>
