<?php
    /** @var $block \MageSuite\ProductTile\Block\Tile */
    /** @var $viewModel \MageSuite\ProductTile\Model\Tile\Fragment\Stock */
    $viewModel = $block->getViewModel();
    $htmlTag = $block->getSectionData('html_tag');
    $cssClass = $block->getSectionData('css_class') ? $block->getSectionData('css_class') : 'cs-product-tile';
    $viewMode = $block->getViewMode();
    $additionalCssClasses = $block->getSectionData('additional_css_classes') ? ' ' .$block->getSectionData('additional_css_classes') : '';
    $viewModeCssClass = ' ' .$cssClass .'--' .$viewMode;
    $entireTileClickable = $block->getSectionData('entire_tile_clickable');
    $entireTileClickableClass = $entireTileClickable ? ' ' .$cssClass .'--clickable' : '';
    $stockCssClasses = !$viewModel->isSaleable($block->getProductEntity()) ? ' ' .$cssClass .'--out-of-stock' : '';
?>

<<?= $htmlTag ?> class="<?= $cssClass .$viewModeCssClass .$entireTileClickableClass .$stockCssClasses . $additionalCssClasses; ?>">
    <?php foreach($this->getChilds() as $child): ?>
        <?= $child->setTile($block)->toHtml(); ?>
    <?php endforeach; ?>
</<?= $htmlTag ?>>
