<?php
// @codingStandardsIgnoreFile

/** @var \MageSuite\ProductTile\Block\Tile\Fragment $block */

/** @var \Magento\Wishlist\Model\Item $item */
$addToCartHelper = $this->helper(\MageSuite\ProductTile\Helper\AddToCart::class);
$item = $block->getTile()->getWishlistItem();
$wishlistHelper = $block->getWishlistHelper();
$product = $block->getTile()->getProductEntity();
$areSwatchesClickable = $block->getVar('configurable_tile_swatches/enabled', 'Magento_Catalog');
$canBeConfigured = !$areSwatchesClickable && $addToCartHelper->canBeConfigured($product);
$showWishlistQtySwitcher = $block->getShowWishlistQtySwitcher();
?>
<div class="cs-product-tile__addtocart cs-addtocart cs-addtocart--wishlist">

    <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility() && $product->isSaleable() && $showWishlistQtySwitcher && !$canBeConfigured): ?>
        <?= $this->getLayout()
            ->createBlock(Magento\Framework\View\Element\Template::class)
            ->setInputName('qty[' . $block->escapeHtmlAttr($item->getId()) . ']')
            ->setInputInitialValue((int)(($item->getQty() ?? 1) * 1))
            ->setInputAdditionalParams('id="qty[' . $block->escapeHtmlAttr($item->getId()) . ']" data-role="qty" min="1"')
            ->setDecrementIconUrl($block->getVar('qty_increment/icons/decrement', 'MageSuite_ThemeHelpers'))
            ->setIncrementIconUrl($block->getVar('qty_increment/icons/increment', 'MageSuite_ThemeHelpers'))
            ->setTemplate($block->getVar('qty_increment/template', 'MageSuite_ThemeHelpers'))
            ->setAdditionalCssClasses($block->getWishlistQtyClass())
            ->toHtml();
        ?>
    <?php endif; ?>
    <?php if ($product->isSaleable()): ?>
        <!-- <button type="button" data-role="tocart" data-post='<?= /* @noEscape */ $wishlistHelper->getAddToCartParams($item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>" class="action tocart primary">
            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
        </button> -->
        <?= $block->getChildBlock('atc.button')
            ->setTile($block->getTile())
            ->setAddtocartLabel($block->getAtcAddLabel())
            ->setCanBeConfigured($canBeConfigured)
            ->setButtonType('button')
            ->setButtonParams('data-role="tocart" data-post=\'' . $wishlistHelper->getAddToCartParams($item) . '\' title="' . $block->escapeHtmlAttr(__('Add to Cart')) . '" data-item-id="' . $block->escapeHtmlAttr($item->getId()) . '"')
            ->toHtml();
        ?>
    <?php endif; ?>
</div>