<?php
/**
 * @var \MageSuite\ProductTile\Block\Tile\Fragment $block
 * @var \Magento\Framework\Escaper $escaper
*/

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getTile()->getWishlistItem();
$itemId = $item->getWishlistItemId();
$wishlistHelper = $block->getWishlistHelper();
$productName = $block->getTile()->getProductEntity()->getName();
?>

<div class="field comment-box">
    <label class="label" for="product-item-comment-<?= $escaper->escapeHtmlAttr($itemId); ?>">
        <span><?= $escaper->escapeHtml($productName) . ' - ' . $escaper->escapeHtml(__('Comment')) ?></span>
    </label>
    <div class="control">
        <textarea
            id="product-item-comment-<?= $escaper->escapeHtmlAttr($itemId); ?>"
            placeholder="<?= /* @noEscape */ $wishlistHelper->defaultCommentString() ?>"
            autocomplete="off"
            name="description[<?= $itemId ?>]"
            class="product-item-comment input-text"
        ><?= ($escaper->escapeHtml($item->getDescription())) ?></textarea>
    </div>
</div>
