<?php
/* @var \MageSuite\ProductTile\Block\Tile\Fragment $block */
/* @var \Magento\Wishlist\Model\Item $item */
$wishlistItem = $block->getTile()->getWishlistItem();
$wishlistHelper = $block->getWishlistHelper();
$product = $block->getTile()->getProductEntity();
$linkCssClass = $block->getLinkCssClass() ? 'class="'.$block->getLinkCssClass().'"' : '';
?>

<?php if ($wishlistItem): ?>
    <a
            href="#"
            data-role="remove"
            data-post-remove='<?php /* @escapeNotVerified */ echo $wishlistHelper->getRemoveParams($wishlistItem); ?>'
            title="<?= $block->getLinkLabel() ?>"
            <?= $linkCssClass ?>
    ><?= $block->getChildHtml('') ?><?= $block->getLinkLabel() ?></a>
<?php endif ?>
