<?php
/** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
$dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');
$dailyDealData = $dailyDealHelper->prepareOfferData($block->getProduct());
?>
<?php if($dailyDealData and $dailyDealData['deal'] and in_array($dailyDealData['displayType'], ['badge', 'badge_counter'])): ?>
    <span class="cs-dailydeal__badge cs-dailydeal__badge--label">
        <span class="cs-dailydeal__badge-content"><?= __('Limited offer!') ?></span>
    </span>
    <?php if ($dailyDealData['items'] && $dailyDealData['items'] > 0): ?>
        <span class="cs-dailydeal__badge">
            <span class="cs-dailydeal__badge-content"><?= __('%1 item(s) left', $dailyDealData['items']) ?></span>
        </span>
    <?php endif; ?>
<?php endif; ?>
