<?php
    /** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
    $dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');
    $dailyDealData = $dailyDealHelper->prepareOfferData($block->getProduct());

    $oldDiscount = $dailyDealData && $dailyDealData['deal'] ? $dailyDealData['oldDiscount'] : '';

    $cssClass = $block->getCssClass();
    $cssClass = !empty($cssClass) ? sprintf('class="%s"', $cssClass) : '';

    $valuePrefix = $block->getValuePrefix();
    $valueSuffix = $block->getValueSuffix();
?>
<?php if ($oldDiscount and $dailyDealData['displayType'] === 'badge_counter'): ?>
    <span <?= $cssClass ?>>
        <span class="cs-badge__span"><?= $valuePrefix ?><?= $oldDiscount ?><?= $valueSuffix ?></span>
    </span>
<?php endif; ?>
