<?php
    /** @var \MageSuite\ProductTile\Block\Tile\Fragment $block */
    $viewModel = $block->getViewModel();

    $isVisible = $viewModel->isVisible($block->getTile());
    $badgeValue = $viewModel->getValue($block->getTile());
    $cssModifier = $viewModel->getCssModifier($block->getTile());

    $product = $block->getProduct();
    $htmlTag = $block->getHtmlTag();
    $cssClass = implode(' ', [$block->getCssClass(), $cssModifier]);
    $cssClass = !empty($cssClass) ? sprintf('class="%s"', $cssClass) : '';
    $labelCssClass = $block->getLabelCssClass() ? 'class="'.$block->getLabelCssClass().'"' : '';
    $valueCssClass = $block->getValueCssClass() ? 'class="'.$block->getValueCssClass().'"' : '';
    $label = $block->getLabel();
    $labelPrefix = $block->getLabelPrefix();
    $labelSuffix = $block->getLabelSuffix();

?>
<?php if($isVisible): ?>
    <<?= $htmlTag ?> <?= $cssClass ?>">
        <?php if(!empty($labelPrefix)): ?>
            <?= $labelPrefix ?>
        <?php endif; ?>
        <?php if(!empty($label)): ?>
            <span <?= $labelCssClass ?>><?= $label ?></span>
        <?php endif; ?>
        <?php if(!empty($badgeValue)): ?>
            <span <?= $valueCssClass ?>><?= $badgeValue ?></span>
        <?php endif; ?>
        <?php if(!empty($labelSuffix)): ?>
            <?= $labelSuffix ?>
        <?php endif; ?>
    </<?= $htmlTag ?>>
<?php endif; ?>
