<?php
    /** @var \MageSuite\ProductTile\Block\Tile\Fragment $block */
    $viewModel = $block->getViewModel();
    $isVisible = $viewModel->isVisible($block->getTile());
    $badgeValue = $viewModel->getValue($block->getTile());
    $label = $block->getLabel();
?>
<?php if($isVisible && ($badgeValue || !empty($label))): ?>
    <?php 
        $wrapperTag = $block->getWrapperTag() ? $block->getWrapperTag() : 'li';
        $wrapperClass = $block->getWrapperCssClass() ? sprintf('class="%s"', $block->getWrapperCssClass()) : '';
        $badgeTextClass = $block->getTextCssClass() ? sprintf('class="%s"', $block->getTextCssClass()) : '';
        $cssModifier = $viewModel->getCssModifier($block->getTile());
        $cssClass = implode(' ', [$block->getCssClass(), $cssModifier]);
        $cssClass = !empty($cssClass) ? sprintf('class="%s"', $cssClass) : '';

        $valuePrefix = $block->getValuePrefix();
        $valueSuffix = $block->getValueSuffix();
    ?>
    <<?= $wrapperTag ?> <?= $wrapperClass ?>>
        <span <?= $cssClass ?>>
            <span <?= $badgeTextClass ?>><?= $label ?><span><?= $valuePrefix ?><?= $badgeValue ?><?= $valueSuffix ?></span></span>
        </span>
    </<?= $wrapperTag ?>>
<?php endif; ?>
