<?php if ($block->getTile()->getViewMode() == 'teaser'): ?>
    <?php
        $specialDescription = $block->getTile()->getSpecialDescription();
    ?>
    <?php if ($specialDescription): ?>
        <?= $specialDescription ?>
    <?php else: ?>
        <?= $block->getProduct()->getShortDescription() ?>
    <?php endif; ?>
<?php else: ?>
    <?= $block->getProduct()->getShortDescription() ?>
<?php endif; ?>