<?php
/** @var \MageSuite\ProductTile\Block\Tile\Fragment $block */
/** @var \MageSuite\ProductTile\Model\Tile\Fragment\Gallery\Images $viewModel */
$viewModel = $block->getViewModel();
$product = $block->getProduct();

// Tile gallery images
$tileImage = $block->getTileImageId();
$tileImage2x = $block->getTileImageId2x();
$limit = $block->getItemLimit();

// Images that will be switched as main image
$productImage = $block->getProductImageId();
$productImage2x = $block->getProductImageId2x();

$images = $viewModel->getMediaGalleryImages($product, $tileImage, $tileImage2x, $limit, $productImage, $productImage2x);
$displayRule = $block->getDisplayIfSingle() ? count($images) : count($images) > 1;
$loaderImage = 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
?>

<?php if($images && $displayRule): ?>
    <?php
        $containerTag = $block->getContainerTag() ?? 'ul';
        $containerClass = $block->getContainerCssClass();
        $containerClass = $containerClass ? sprintf('class="%s"', $containerClass) : '';

        $wrapperTag = $block->getWrapperTag() ?? 'li';
        $wrapperClass = $block->getWrapperCssClass();
        $wrapperClass = $wrapperClass ? sprintf('class="%s"', $wrapperClass) : '';

        $thumbnailCssClass = $block->getThumbnailCssClass();
        $thumbnailCssClass = $thumbnailCssClass ? sprintf('class="%s"', $thumbnailCssClass) : '';
    ?>
    <<?= $containerTag ?> <?= $containerClass ?>>
    <?php foreach($images as $imagesSet): ?>
        <<?= $wrapperTag ?> <?= $wrapperClass ?>>
            <picture <?= $thumbnailCssClass ?>>
                <source
                    srcset="<?= $imagesSet['tileImageSrcSet'] ?>"
                >
                <img
                    src="<?= $imagesSet['tileImageSrc'] ?>"
                    srcset="<?= $imagesSet['tileImageSrcSet'] ?>"
                    data-product-image-src="<?= $imagesSet['productImageSrc'] ?>"
                    data-product-image-srcset="<?= $imagesSet['productImageSrcSet'] ?>"
                    width="<?= $imagesSet['width'] ?>"
                    height="<?= $imagesSet['height'] ?>"
                    alt="<?= $block->escapeHtmlAttr($product->getName()) ?>"
                    loading="lazy"
                >
            </picture>
        </<?= $wrapperTag ?>>
    <?php endforeach; ?>
    </<?= $containerTag ?>>
<?php endif; ?>
