<?php
/** @var \MageSuite\ProductTile\Block\Tile\Fragment $block */
/** @var \MageSuite\ProductTile\Model\Tile\Fragment\Gallery\Images $viewModel */
$viewModel = $block->getViewModel();
$product = $block->getProduct();

// Tile gallery images
$tileImage = $block->getTileImageId();
$tileImage2x = $block->getTileImageId2x();
$limit = $block->getItemLimit();

// Images that will be switched as main image
$productImage = $block->getProductImageId();
$productImage2x = $block->getProductImageId2x();

$images = $viewModel->getMediaGalleryImages($product, $tileImage, $tileImage2x, $limit, $productImage, $productImage2x);
$displayRule = $block->getDisplayIfSingle() ? count($images) : count($images) > 1;
$imageTypeHelper = $this->helper(\MageSuite\ThemeHelpers\Helper\ImageType::class);
$loaderImage = 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
?>

<?php if($images && $displayRule): ?>
    <?php
        $containerTag = $block->getContainerTag() ?? 'ul';
        $containerClass = $block->getContainerCssClass();
        $containerClass = $containerClass ? sprintf('class="%s"', $containerClass) : '';

        $wrapperTag = $block->getWrapperTag() ?? 'li';
        $wrapperClass = $block->getWrapperCssClass();
        $wrapperClass = $wrapperClass ? sprintf('class="%s"', $wrapperClass) : '';

        $thumbnailCssClass = $block->getThumbnailCssClass();
        $thumbnailCssClass = $thumbnailCssClass ? sprintf('class="%s"', $thumbnailCssClass) : '';
    ?>
    <<?= $containerTag ?> <?= $containerClass ?>>
    <?php foreach($images as $imagesSet): ?>
        <?php
            $isWebpSupported = $imageTypeHelper->supportsWebp($imagesSet['tileImageSrc']);
        ?>
        <<?= $wrapperTag ?> <?= $wrapperClass ?>>
            <picture <?= $thumbnailCssClass ?>>
                <?php if ($isWebpSupported): ?>
                    <source
                        type="image/webp"
                        srcset="<?= $loaderImage ?>"
                        data-srcset="<?= $imagesSet['webpTileImageSrcSet'] ?>"
                    >
                <?php endif; ?>
                <source
                    srcset="<?= $loaderImage ?>"
                    data-srcset="<?= $imagesSet['tileImageSrcSet'] ?>"
                >
                <img
                    src="<?= $loaderImage ?>"
                    class="lazyload"
                    data-src="<?= $imagesSet['tileImageSrc'] ?>"
                    data-srcset="<?= $imagesSet['tileImageSrcSet'] ?>"
                    data-product-image-src="<?= $imagesSet['productImageSrc'] ?>"
                    data-product-image-srcset="<?= $imagesSet['productImageSrcSet'] ?>"
                    width="<?= $imagesSet['width'] ?>"
                    height="<?= $imagesSet['height'] ?>"
                    alt="<?= $block->escapeHtmlAttr($product->getName()) ?>"
                >
            </picture>
        </<?= $wrapperTag ?>>
    <?php endforeach; ?>
    </<?= $containerTag ?>>
<?php endif; ?>
