<?php
    $product = $block->getProduct();
    $imageHelper = $this->helper('Magento\Catalog\Helper\Image');
    $productImage = $imageHelper->init($product, 'category_page_grid');
    $productImageUrl = $productImage->getUrl();
    $productImage2x = $imageHelper->init($product, $block->getImage2xId() ?? 'category_page_grid_x2');
    $productImage2xUrl = $productImage2x->getUrl();
    $productImageSize = $productImage->getResizedImageInfo();

    $productImageLazyloadFrom = $block->getVar('product_image_lazyload_from') ?? 7;
    $productIterator = $block->getTile()->getIterator();
    $productImageLazyloaded = $productIterator >= $productImageLazyloadFrom;

    /* XML config */
    $cssClass = $block->getCssClass();
?>
<?php if ($productImageLazyloaded): ?>
<img 
    class="<?= $cssClass ?> lazyload" 
    src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
    data-src="<?= $productImageUrl ?>" 
    data-srcset="<?= $productImageUrl . ' 1x, ' . $productImage2xUrl . ' 2x' ?>"
    width="<?= $productImageSize[0] ?>" 
    height="<?= $productImageSize[1] ?>" 
    alt="<?= $product->getName() ?>"
>
<noscript>
    <img
        class="<?= $cssClass ?>" 
        src="<?= $productImageUrl ?>" 
        srcset="<?= $productImageUrl . ' 1x, ' . $productImage2xUrl . ' 2x' ?>"
        width="<?= $productImageSize[0] ?>" 
        height="<?= $productImageSize[1] ?>" 
        alt="<?= $product->getName() ?>"
    >
</noscript>
<?php else: ?>
<img
    class="<?= $cssClass ?>" 
    src="<?= $productImageUrl ?>" 
    srcset="<?= $productImageUrl . ' 1x, ' . $productImage2xUrl . ' 2x' ?>"
    width="<?= $productImageSize[0] ?>" 
    height="<?= $productImageSize[1] ?>" 
    alt="<?= $product->getName() ?>"
>
<?php endif; ?>