<?php
    $product = $block->getProduct();
    $imageHelper = $this->helper('Magento\Catalog\Helper\Image');
    $productImage = $block->getImage($product, 'category_page_grid');
    $productImageUrl = $block-> escapeUrl($productImage->getImageUrl());
    $productImage2x = $block->getImage($product, $block->getImage2xId() ?? 'category_page_grid_x2');
    $productImage2xUrl = $block->escapeUrl($productImage2x->getImageUrl());
    $productImageWidth = $productImage->getWidth();
    $productImageHeight = $productImage->getHeight();

    $productImageAlt = $block->escapeHtmlAttr($product->getName());
    $imageTypeHelper = $this->helper(\MageSuite\ThemeHelpers\Helper\ImageType::class);
    $isWebpSupported = $imageTypeHelper->supportsWebp($productImageUrl);

    $loaderImage = 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';

    /* XML config */
    $cssClass = $block->getCssClass();
    $imgClass = $block->getImgClass();
    $applyWidthHeightAttr = $block->getApplyWidthHeightAttr();
?>
<picture class="<?= $cssClass ?>">
    <?php if ($isWebpSupported): ?>
        <source
            type="image/webp"
            srcset="<?= $loaderImage ?>"
            data-srcset="<?= $productImageUrl . '.webp 1x, ' . $productImage2xUrl . '.webp 2x' ?>"
        >
    <?php endif; ?>
    <source
        srcset="<?= $loaderImage ?>"
        data-srcset="<?= $productImageUrl . ' 1x, ' . $productImage2xUrl . ' 2x' ?>"
    >
    <img
        src="<?= $loaderImage ?>"
        class="lazyload <?= $imgClass ?>"
        data-src="<?= $productImageUrl ?>"
        data-srcset="<?= $productImageUrl . ' 1x, ' . $productImage2xUrl . ' 2x' ?>"
        <?php if ($applyWidthHeightAttr): ?>
        width="<?= $productImageWidth ?>"
        height="<?= $productImageHeight ?>"
        <?php endif; ?>
        alt="<?= $productImageAlt ?>"
    >
</picture>
<noscript>
    <img
        class="<?= $cssClass ?>"
        src="<?= $productImageUrl ?>"
        srcset="<?= $productImageUrl . ' 1x, ' . $productImage2xUrl . ' 2x' ?>"
        <?php if ($applyWidthHeightAttr): ?>
        width="<?= $productImageWidth ?>"
        height="<?= $productImageHeight ?>"
        <?php endif; ?>
        alt="<?= $productImageAlt ?>"
    >
</noscript>
