<?php
    $product = $block->getProduct();
    $imageHelper = $this->helper('Magento\Catalog\Helper\Image');
    $productImage = $block->getImage($product, 'category_page_grid');
    $productImageUrl = $productImage->getImageUrl();
    $productImage2x = $block->getImage($product, $block->getImage2xId() ?? 'category_page_grid_x2');
    $productImage2xUrl = $productImage2x->getImageUrl();
    $productImageSize = $productImage->getResizedImageInfo();

    /* XML config */
    $cssClass = $block->getCssClass();
?>
<img 
    class="<?= $cssClass ?> lazyload" 
    src="<?= $productImageUrl ?>"
    srcset="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" 
    data-srcset="<?= $productImageUrl . ' 1x, ' . $productImage2xUrl . ' 2x' ?>"
    width="<?= $productImageSize[0] ?>" 
    height="<?= $productImageSize[1] ?>" 
    alt="<?= $product->getName() ?>"
>
<noscript>
    <img
        class="<?= $cssClass ?>" 
        src="<?= $productImageUrl ?>" 
        srcset="<?= $productImageUrl . ' 1x, ' . $productImage2xUrl . ' 2x' ?>"
        width="<?= $productImageSize[0] ?>" 
        height="<?= $productImageSize[1] ?>" 
        alt="<?= $product->getName() ?>"
    >
</noscript>