<?php
    /** @var MageSuite\ProductTile\Block\Tile\Fragment\Review $viewModel */
    $viewModel = $block->getViewModel();
    $product = $block->getProduct();
    $reviewsCount = $viewModel->getReviewsCount($product);
?>

<?php if($reviewsCount > 0): ?>
    <?php 
        $htmlTag = !empty($block->getHtmlTag()) ? $block->getHtmlTag() : 'div';
        $cssClass = $block->getCssClass() ? 'class="'.$block->getCssClass().'"' : ''; 
    ?>
    <<?= $htmlTag ?> <?= $cssClass ?>>
        <?= $this->getLayout()
                 ->createBlock(\Magento\Framework\View\Element\Template::class)
                 ->setMaxStars(5)
                 ->setActiveStars($viewModel->getActiveStars($product))
                 ->setReviewsCount($reviewsCount)
                 ->setTemplate('Magento_Review::rating-stars.phtml')
                 ->toHtml();
        ?>
    </<?= $htmlTag ?>>
<?php endif; ?>
