<?php
    /** @var MageSuite\ProductTile\Model\Tile\Fragment\Review $viewModel */
    $viewModel = $block->getViewModel();
    $product = $block->getProduct();
    $reviewsCount = $viewModel->getReviewsCount($product);
    $showIfNoReviews = $block->getShowIfNoReviews() ?? false;
?>

<?php if($reviewsCount > 0 || $showIfNoReviews): ?>
    <?php 
        $htmlTag = $block->getHtmlTag() ?? 'div';
        
        $cssClass = $block->getCssClass(); 
        $cssClass = $cssClass ? 'class="'.$cssClass.'"' : ''; 
    ?>
    <<?= $htmlTag ?> <?= $cssClass ?>>
        <?= $this->getLayout()
                 ->createBlock(\Magento\Framework\View\Element\Template::class)
                 ->setMaxStars(5)
                 ->setActiveStars($viewModel->getActiveStars($product))
                 ->setReviewsCount($reviewsCount)
                 ->setShowIfNoReviews($showIfNoReviews)
                 ->setTemplate('Magento_Review::rating-stars.phtml')
                 ->toHtml();
        ?>
    </<?= $htmlTag ?>>
<?php endif; ?>
