<?php 
    $product = $block->getProduct();
    $isSaleable = $product->isSaleable();
    $htmlTag = $block->getHtmlTag();
    $cssClass = $block->getCssClass();
    $modifier = $isSaleable ? $block->getInStockCssModifier() : $block->getOutOfStockCssModifier();
    $label = $isSaleable ? $block->getInStockLabel() : $block->getOutOfStockLabel();
    $iconPath = $this->getIconPath();
?>

<<?= $htmlTag; ?> class="<?= $cssClass . ' ' . $modifier ?>">
    <?= $block->getChildHtml() ?>
    <?= $label ?>
</<?= $htmlTag; ?>>
