<?php
    /** @var \MageSuite\ProductTile\Model\Tile\Fragment\Stock $viewModel */
    $viewModel = $block->getViewModel();
    $product = $block->getProduct();
    $isSaleable = $viewModel->isSaleable($product);
    $htmlTag = $block->getHtmlTag();
    $cssClass = $block->getCssClass();
    $modifier = $isSaleable ? $block->getInStockCssModifier() : $block->getOutOfStockCssModifier();
    $label = $isSaleable ? $block->getInStockLabel() : $block->getOutOfStockLabel();
    $iconPath = $this->getIconPath();
?>

<<?= $htmlTag; ?> class="<?= $cssClass . ' ' . $modifier ?>">
    <?= $block->getChildHtml() ?>
    <?= $label ?>
</<?= $htmlTag; ?>>
