<?php
    $product = $block->getProduct();
    $isSaleable = $product->isSaleable();
    /** @var \MageSuite\ProductTile\Helper\AddToCart $addToCartHelper */
    $addToCartHelper = $this->helper(\MageSuite\ProductTile\Helper\AddToCart::class);
    $areSwatchesClickable = $block->getVar('configurable_tile_swatches/enabled', 'Magento_Catalog');
    $canBeConfigured = !$areSwatchesClickable && $addToCartHelper->canBeConfigured($product);
    $showOnlyForSimpeProducts = !$areSwatchesClickable && $block->getShowOnlyForSimpleProducts();
    $label = $canBeConfigured ? $block->getAtcConfigureLabel() : $block->getAtcAddLabel();
    $showQtySwitcher = $block->getShowQtySwitcher();
?>

<?php
    if ($isSaleable && (!$showOnlyForSimpeProducts || $showOnlyForSimpeProducts && $product->getTypeId() == \Magento\Catalog\Model\Product\Type::TYPE_SIMPLE)): ?>
        <?php $postParams = $block->getAddToCartPostParams($product); ?>

        <form<?php if(!$canBeConfigured): ?> data-role="tocart-form"<?php endif; ?> data-product-sku="<?= $block->escapeHtml($product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post" class="<?= $block->getFormClass() ?>">
            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">

            <?php if (isset($postParams['data']['bundle_option']) and !empty($postParams['data']['bundle_option'])): ?>
                <?php foreach ($postParams['data']['bundle_option'] as $optionId => $options): ?>
                    <?php if (count($options) == 1): ?>
                        <input type="hidden" name="bundle_option[<?= $optionId ?>]" value="<?= array_shift($options) ?>"/>
                    <?php else: ?>
                        <?php foreach ($options as $selectionId => $value): ?>
                            <input type="hidden" name="bundle_option[<?= $optionId ?>][<?= $selectionId ?>]" value="<?= $value ?>"/>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php if(!$canBeConfigured and $showQtySwitcher): ?>
                <?= $this->getLayout()
                    ->createBlock(Magento\Framework\View\Element\Template::class)
                    ->setInputName('qty')
                    ->setInputInitialValue((int)(($product->getQty() != 0 ? $product->getQty() : 1) * 1))
                    ->setInputAdditionalParams('type="number" data-role="qty" data-validate="{\'required-number\':true,\'validate-greater-than-zero\':true}"')
                    ->setDecrementIconUrl($block->getVar('qty_increment/icons/decrement', 'MageSuite_ThemeHelpers'))
                    ->setIncrementIconUrl($block->getVar('qty_increment/icons/increment', 'MageSuite_ThemeHelpers'))
                    ->setTemplate($block->getVar('qty_increment/template', 'MageSuite_ThemeHelpers'))
                    ->setAdditionalCssClasses($block->getQtyClass())
                    ->toHtml();
                ?>
            <?php endif; ?>

            <input type="hidden" name="<?= /* @escapeNotVerified */ \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED] ?>">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getChildBlock('atc.button')
                    ->setTile($block->getTile())
                    ->setAddtocartLabel($label)
                    ->setCanBeConfigured($canBeConfigured)
                    ->toHtml();
            ?>
        </form>
    <?php endif;
?>
