<?php 
    $product = $block->getProduct();
    $isSaleable = $product->isSaleable();
    $isConfigurable = $product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE;
    $showButtonWhenNotSaleable = $block->getShowButtonWhenNotSableable();
    $showOnlyForSimpeProducts = $block->getShowOnlyForSimpleProducts();
    $label = $product->getTypeId() == $isConfigurable ? $block->getConfigureLabel() : $block->getAddToCartLabel();
?>

<?php
    if (!$showOnlyForSimpeProducts || $showOnlyForSimpeProducts && $product->getTypeId() == \Magento\Catalog\Model\Product\Type::TYPE_SIMPLE):
        if ($isSaleable || (!$isSaleable && $showButtonWhenNotSaleable)): ?>
            <?php $postParams = $block->getAddToCartPostParams($product); ?>
            <form<?php if(!$isConfigurable): ?> data-role="tocart-form"<?php endif; ?> data-product-sku="<?= $block->escapeHtml($product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post" class="<?= $block->getFormClass() ?>">
                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                <input type="hidden" name="<?= /* @escapeNotVerified */ \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED] ?>">
                <?= $block->getBlockHtml('formkey') ?>
                <button type="submit" title="<?= $label ?>" 
                        class="action tocart primary <?= $block->getButtonClass() ?>"
                        <?php if (!$isSaleable && $showButtonWhenNotSaleable): ?> disabled="disabled"<?php endif ?>
                >
                    <?= $block->getChildHtml('tile.atc.icon'); ?>
                    <span class="<?= $block->getButtonLabelClass() ?>"><?= $label ?></span>
                </button>
            </form>
        <?php endif;
    endif;
?>
