<?php /** @var $block \MageSuite\ProductTile\Block\Tile\Fragment\AddTo\Compare */ ?>
<?php 
    $label = $this->getLabel();
    $postDataParams = $block->getCompareHelper()->getPostDataParams($block->getProduct());
?>

<a href="#"
   class="action tocompare cs-links-block-addto__link"
   title="<?= $label ?>"
   aria-label="<?= $label ?>"
   data-post='<?= $postDataParams ?>'
   role="button">
    <?= $this->getChildHtml() ?>
    <?= $label ?>
</a>
