<?php 
    $product = $block->getProduct();
    $label = $this->getLabel();
    $wishlistItem = $block->getTile()->getWishlistItem();
    $wishlistHelper = $block->getWishlistHelper();
?>

<a href="#" class="towishlist cs-links-block-addto__link" title="<?= $label ?>" aria-label="<?= $label ?>" data-post='<?= $wishlistHelper->getAddParams($product) ?>' data-uenc-update='true' data-action="add-to-wishlist" role="button">
    <?= $this->getChildHtml() ?>
    <span class="cs-links-block-addto__link-label"><?= $label ?></span>
</a>